### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by julianctrt** [slaclab/Simple-ZCU208-Example#3]
Hi, would ike to give a try but seems some parts are missing form other remote repos:

/Simple-ZCU208-Example/firmware/submodules/sysgen-dsp-lib'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

regards,
julian

**Comment by ruck314** [comment]
That is a private submodule repo. But we ended up not using it.  I have removed it from the primary repol

https://github.com/slaclab/Simple-ZCU208-Example/commit/2f6dc68262ffe3766b6619feb9c8442228309ee9
